//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Napier_Bank_Message_Filtering_Service_NEW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Napier_Bank_Message_Filtering_Service_NEW.Resources.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan   +93
        ///Åland   +358-18
        ///Albania   +355
        ///Algeria   +213
        ///American Samoa   +1-684
        ///Andorra   +376
        ///Angola   +244
        ///Anguilla   +1-264
        ///Antigua and Barbuda   +1-268
        ///Argentina   +54
        ///Armenia   +374
        ///Aruba   +297
        ///Ascension   +247
        ///Australia   +61
        ///Australian Antarctic Territory   +672-1
        ///Australian External Territories   +672
        ///Austria   +43
        ///Azerbaijan   +994
        ///Bahamas   +1-242
        ///Bahrain   +973
        ///Bangladesh   +880
        ///Barbados   +1-246
        ///Barbuda   +1-268
        ///Belarus   +375
        ///Belgium   +32
        ///Belize   +501
        ///Benin  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string country_codes {
            get {
                return ResourceManager.GetString("country_codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAP,Always a pleasure
        ///AAR,At any rate
        ///AAS,Alive and smiling
        ///ADN,Any day now
        ///AEAP,As early as possible
        ///AFAIK,As far as I know
        ///AFK,Away from keyboard
        ///AKA,Also known as
        ///AISB,As it should be
        ///AOTA,All of the above
        ///ASAP,As soon as possible
        ///A/S/L,Age/sex/location
        ///AT,At your terminal
        ///ATM,At the moment
        ///AYEC,At your earliest convenience
        ///B/F,Boyfriend
        ///B4,Before
        ///B4N ,Bye for now
        ///BAK,Back at keyboard
        ///BAU,Business as usual
        ///BBIAF,Be back in a few
        ///BBIAM,Be back in a minute
        ///BBL,Be back later
        ///BBS,Be ba [rest of string was truncated]&quot;;.
        /// </summary>
        public static string textwords {
            get {
                return ResourceManager.GetString("textwords", resourceCulture);
            }
        }
    }
}
